### ISSUE TITLE
skinsdb is missing player_api

### ISSUE THREAD

**Issue by kneekoo** [minetest-mods/skinsdb#86] opened 2023-04-14 15:03 UTC
I assume `player_api` existed on ContentDB, but currently it's gone, and new installs of SkinsDB are no longer functional.

**Comment by bell07** [comment] 2023-04-14 15:23
player_api is part of minetest_game and some other games, like https://content.minetest.net/modnames/player_api/

**Comment by SmallJoker** [comment] 2023-04-14 19:31
Adding player_api to CDB or handling dependency management is not the responsibility of the skinsdb mod. You should report your problem to the CDB repository. Aside from that, it clearly mentions that the mod is not found using the game (and global mods) that you specified.

**Comment by kneekoo** [comment] 2023-04-14 20:32
My point is that this issue is not something an average (or new) player can fix. I'll file an issue with Minetest, because this should be handled better for the user, especially with 5.7.0 no longer starting the worlds with unmet dependencies.

**Comment by mckaygerhard** [comment] 2023-08-07 12:54
hi @kneekoo  .. if fill an issue agains "minetest" trolltest they just will ignore or bypass you.. the problem is that the interface causes more danger than solution, in previous days an user must READ the README of each mod and was forced to KNOW what to do.. 

nowadays the user just think with two click will reach everything

**WHAT IS THE PROBLEM?** you are using the Mineclone2 sub game, the mod in dependency `player_api` has a different name in such sub game.. that's all

**WHAT YOU MUST DO?** for all its better, event just think that the click of mouse solves all, maybe reading first before click is better, to get proper information

**WHAT SOLUTIONS WE HAVE?** well, mineclone2 has a similar mod that offers similar functionality @SmallJoker  was not offers to made a patch (a portion of code that introduces a trick to address the situation)

i chekc the mineclone2 and maybe i will add suppor for the OldCoder minetest mods at minenux project https://git.minetest.io/minenux .. stay tuned

**Comment by rubenwardy** [comment] 2023-08-08 10:11
SkinsDB does not currently support Mineclone2, it only supports MTG and those that include MTG's player_api

SkinsDB could fix this issue by adding support for Mineclone2

I plan on making it clearer when a game isn't supported in the Minetest client. ContentDB already has the foundations for this (see compatible/supported games) in the web UI, I plan to promote packages that support the current game in the ContentDB dialog and also show better warning messages when the user tries to select a mod that does not support the current game. The issue for this is https://github.com/minetest/minetest/issues/12034

**Comment by SmallJoker** [comment] 2024-03-05 18:23
Closing: skinsdb is not responsible for fixing this issue. Feel free to provide a PR that would then make use of equivalent MineClone2 functions to turn `player_api` into a soft dependency.

**Closed by SmallJoker** 2024-03-05 18:23 UTC
